/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Variant({
  'Arts' : IDL.Null,
  'Commerce' : IDL.Null,
  'Science' : IDL.Null,
});
export const Level = IDL.Variant({
  'Postgraduate' : IDL.Null,
  'Undergraduate' : IDL.Null,
  'Doctoral' : IDL.Null,
});
export const SubjectIdentifier = IDL.Text;
export const TopicIdentifier = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const StudyMaterial = IDL.Record({
  'title' : IDL.Text,
  'file' : ExternalBlob,
});
export const Topic = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'studyMaterials' : IDL.Vec(StudyMaterial),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'level' : Level,
  'category' : Category,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SubjectContent = IDL.Record({
  'description' : IDL.Text,
  'topics' : IDL.Vec(Topic),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCourse' : IDL.Func([IDL.Text, IDL.Text, Category, Level], [], []),
  'addDefaultCourses' : IDL.Func([], [], []),
  'addTopicToSubject' : IDL.Func(
      [SubjectIdentifier, TopicIdentifier, Topic],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'courseExists' : IDL.Func([Category, Level], [IDL.Bool], ['query']),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([IDL.Nat], [Course], ['query']),
  'getCoursesByCategory' : IDL.Func([Category], [IDL.Vec(Course)], ['query']),
  'getSubjectContent' : IDL.Func(
      [SubjectIdentifier],
      [SubjectContent],
      ['query'],
    ),
  'getSubjectDescription' : IDL.Func(
      [SubjectIdentifier],
      [IDL.Text],
      ['query'],
    ),
  'getTopic' : IDL.Func([TopicIdentifier], [Topic], ['query']),
  'getTopicsBySubject' : IDL.Func(
      [SubjectIdentifier],
      [IDL.Vec(IDL.Tuple(TopicIdentifier, Topic))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setSubjectDescription' : IDL.Func([SubjectIdentifier, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Variant({
    'Arts' : IDL.Null,
    'Commerce' : IDL.Null,
    'Science' : IDL.Null,
  });
  const Level = IDL.Variant({
    'Postgraduate' : IDL.Null,
    'Undergraduate' : IDL.Null,
    'Doctoral' : IDL.Null,
  });
  const SubjectIdentifier = IDL.Text;
  const TopicIdentifier = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const StudyMaterial = IDL.Record({
    'title' : IDL.Text,
    'file' : ExternalBlob,
  });
  const Topic = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'studyMaterials' : IDL.Vec(StudyMaterial),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'level' : Level,
    'category' : Category,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SubjectContent = IDL.Record({
    'description' : IDL.Text,
    'topics' : IDL.Vec(Topic),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCourse' : IDL.Func([IDL.Text, IDL.Text, Category, Level], [], []),
    'addDefaultCourses' : IDL.Func([], [], []),
    'addTopicToSubject' : IDL.Func(
        [SubjectIdentifier, TopicIdentifier, Topic],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'courseExists' : IDL.Func([Category, Level], [IDL.Bool], ['query']),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([IDL.Nat], [Course], ['query']),
    'getCoursesByCategory' : IDL.Func([Category], [IDL.Vec(Course)], ['query']),
    'getSubjectContent' : IDL.Func(
        [SubjectIdentifier],
        [SubjectContent],
        ['query'],
      ),
    'getSubjectDescription' : IDL.Func(
        [SubjectIdentifier],
        [IDL.Text],
        ['query'],
      ),
    'getTopic' : IDL.Func([TopicIdentifier], [Topic], ['query']),
    'getTopicsBySubject' : IDL.Func(
        [SubjectIdentifier],
        [IDL.Vec(IDL.Tuple(TopicIdentifier, Topic))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setSubjectDescription' : IDL.Func([SubjectIdentifier, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };